"""add keep_tracks to encode jobs

Revision ID: 34337d05c76b
Revises: e4e638f9ab87
Create Date: 2026-08-13 15:19:22.235934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34337d05c76b'
down_revision: Union[str, None] = 'e4e638f9ab87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keep_tracks', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.drop_column('keep_tracks')

    # ### end Alembic commands ###
