"""initial_library_preview

Revision ID: 825557241666
Revises: 
Create Date: 2026-08-13 01:45:52.772482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825557241666'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encode_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('preset', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('dest_path', sa.String(length=1024), nullable=True),
    sa.Column('output_size', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('library_file_id', sa.Integer(), nullable=True),
    sa.Column('parent_job_id', sa.Integer(), nullable=True),
    sa.Column('frame_offset', sa.Integer(), nullable=False),
    sa.Column('align_confidence', sa.Float(), nullable=True),
    sa.Column('source_clip_path', sa.String(length=1024), nullable=True),
    sa.Column('dest_clip_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_file_id'], ['library_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['encode_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_frames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('source_png', sa.String(length=1024), nullable=False),
    sa.Column('dest_png', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['encode_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparison_frames')
    op.drop_table('encode_jobs')
    op.drop_table('library_files')
    # ### end Alembic commands ###
