"""store_offset_locked_and_compression

Revision ID: d7a51ed7a92e
Revises: 34337d05c76b
Create Date: 2026-08-13 16:34:50.150836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a51ed7a92e'
down_revision: Union[str, None] = '34337d05c76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offset_locked', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('compression_ratio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.drop_column('compression_ratio')
        batch_op.drop_column('offset_locked')

    # ### end Alembic commands ###
