"""add_noise_metrics_and_encode_duration

Revision ID: e4e638f9ab87
Revises: 825557241666
Create Date: 2026-08-13 20:01:17.119139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e638f9ab87'
down_revision: Union[str, None] = '825557241666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('noise_ssim_mean', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('noise_ssim_std', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('noise_psnr_mean', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('noise_psnr_std', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('noise_mse_mean', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('noise_mse_std', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('noise_frame_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('encode_duration_seconds', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encode_jobs', schema=None) as batch_op:
        batch_op.drop_column('encode_duration_seconds')
        batch_op.drop_column('noise_frame_count')
        batch_op.drop_column('noise_mse_std')
        batch_op.drop_column('noise_mse_mean')
        batch_op.drop_column('noise_psnr_std')
        batch_op.drop_column('noise_psnr_mean')
        batch_op.drop_column('noise_ssim_std')
        batch_op.drop_column('noise_ssim_mean')

    # ### end Alembic commands ###
